services:
  - type: web
    name: audit-fup-backend
    region: oregon
    env:
      - fromGroup: audit-fup-env
      - key: DB_TYPE
        value: postgresql
      - key: DB_HOST
        fromService: audit-fup-db
      - key: DB_USER
        fromService: audit-fup-db
      - key: DB_PASSWORD
        fromService: audit-fup-db
      - key: DB_NAME
        fromService: audit-fup-db
    buildCommand: npm install
    startCommand: node src/index.js
    autoDeploy: true

  - type: pserv
    name: audit-fup-db
    region: oregon
    plan: free
    postgresVersion: 16
    postgresMachine: burstable